### ISSUE TITLE
Issue dependency urllib3 version

### ISSUE THREAD

**Issue by Simmoril-QC** [dicksondickson/lora-ease-wsl#2]
Hi, 
During the installation I received this error:
```
_ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
matrix-client 0.4.0 requires urllib3~=1.21, but you have urllib3 2.1.0 which is incompatible._
```
and this:
```
Traceback (most recent call last):
  File "C:\Users\XXXXX\Desktop\lora_ease-wsl\lora-ease-wsl\app.py", line 34, in <module>
    import spaces
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\spaces\__init__.py", line 10, in <module>
    from .zero.decorator import GPU
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\spaces\zero\decorator.py", line 21, in <module>
    from .wrappers import regular_function_wrapper
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\spaces\zero\wrappers.py", line 15, in <module>
    from multiprocessing.context import ForkProcess
ImportError: cannot import name 'ForkProcess' from 'multiprocessing.context' (C:\Users\XXXXX\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py)
```
Any idea what I am doing wrong ? Should I "down-version" at no cost urllib3 to be able to use the app?
Thanks

**Comment by dicksondickson** [comment]
urllib3 warning should be fine. I think your problem is missing the "spaces" package.

did you `pip install -r requirements_local.txt` ?

Also, this really needs to be run inside WSL with Ubuntu distro. Getting this to run on Windows native is going to take some time to untangle.

**Comment by Simmoril-QC** [comment]
Gotcha. Indeed I did copy paste from the github instruction site instead of reading the file in the folder. So solved for the lib.
And for the second topic I will install WSL though, I thought it could run that way.

Thank you for your answer.
